version: '3'

services:

    # db:
    #     image: mysql:8.0.20
    #     command: --default-authentication-plugin=mysql_native_password
    #     env_file:
    #         - .env
    #     container_name: ${APP_NAME}_db
    #     restart: unless-stopped
    #     volumes:
    #         - ./data/:/var/lib/mysql
    #     environment:
    #         MYSQL_DATABASE: ${DB_DATABASE}
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #         MYSQL_USER: ${DB_USERNAME}
    #         MYSQL_PASSWORD: ${DB_PASSWORD}
    #     networks:
    #         - app-network

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        env_file:
            - .env
        container_name: ${APP_NAME}_php
        restart: unless-stopped
        volumes:
            - ./api/:/var/www/api/
        networks:
            - app-network
            
    api:
        build:
            context: .
            dockerfile: docker/api/Dockerfile
        container_name: ${APP_NAME}_api
        restart: unless-stopped
        volumes:
            - ./docker/nginx_includes/:/etc/nginx/includes
            - ./api/:/var/www/api/
            - ./data/certbot/conf:/etc/letsencrypt
        ports:
            - ${API_PORT}:443
        external_links:
            - api
        networks:
            - app-network


networks:
    app-network:
