version: '3'
services:

  #Composer Service
  composer:
    image: composer:1.10
    working_dir: /var/www/api/
    volumes:
      - ./api:/var/www/api/

  #Node Service
  node:
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app
